---
generic-service:
  nameOverride: hmpps-community-accommodation-wiremock

  replicaCount: 4

  image:
    repository: quay.io/hmpps/hmpps-community-accommodation-wiremock
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    hosts:
      - app-hostname.local # override per environment
    tlsSecretName: hmpps-community-accommodation-wiremock # override per environment
    v1_2_enabled: true
    v0_47_enabled: false

  livenessProbe:
    httpGet:
      path: /__admin


  readinessProbe:
    httpGet:
      path: /__admin

  custommetrics:
    enabled: false

  allowlist:
    office: '217.33.148.210/32'
    health-kick: '35.177.252.195/32'
    petty-france-wifi: '213.121.161.112/28'
    global-protect: '35.176.93.186/32'
    mojvpn: '81.134.202.29/32'
    cloudplatform-live1-1: '35.178.209.113/32'
    cloudplatform-live1-2: '3.8.51.207/32'
    cloudplatform-live1-3: '35.177.252.54/32'

generic-prometheus-alerts:
  targetApplication: hmpps-community-accommodation-wiremock
